### ISSUE TITLE
Broken Script

### ISSUE THREAD

**Issue by 641i130** [IsaiahWitzke/LaunchKeyInput#1]
I can't get it to work. There are just too many errors. I'd like to add to this script once it works though... I'll keep attempting to fix it if you don't want to.

**Comment by IsaiahWitzke** [comment]
Woah... Ngl I kinda forgot about this project. I'll try to fix it (but no guarantees on when, am kinda busy atm!).

If you want to take a crack at it, go for it! But be warned: I think this was one of my first attempts to use python, so I apologize for whatever you may find here 😬😬

**Comment by IsaiahWitzke** [comment]
Also, heads up: script was originally created to work for *launch key mini* and Ubuntu...

**Comment by 641i130** [comment]
lol that's all fine; I'm on Linux so it should transfer over a little bit;

**Comment by 641i130** [comment]
I got it to blink!!! I'll submit a pull request once I organize it all nicely.

**Comment by IsaiahWitzke** [comment]
Nice! I'll try to test it on my launchkey as well once you put it up
